[project]
name = "cliente-servidor"
version = "0.1.0"
description = "Proyectos del curso de arquitectura cliente servidor, entrenamiento de modelos de IA locales y distribuidos"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "black>=26.3.1",
    "kagglehub>=1.0.0",
    "loky>=3.5.6",
    "matplotlib>=3.10.8",
    "numpy>=2.2.6",
    "pandas>=2.3.3",
    "psutil>=7.2.2",
    "py-cpuinfo>=9.0.0",
    "rich>=14.3.3",
    "torch>=2.11.0",
    "torchvision>=0.26.0",
]

[tool.black]
line-length = 88
target-version = ['py38']

[dependency-groups]
dev = [
    "isort>=8.0.1",
]

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
